name    = "ai_voice_assistant"
version = "0.1.0"

[dependencies]
std      = "0.10.4"
http     = "0.10.4"
net      = "0.10.4"
encoding = "0.10.4"
fs       = "0.10.4"
record   = "0.10.4"
ml       = "0.10.4"

[entrypoints]
chat  = "ai_voice_assistant/main::chat"
voice = "ai_voice_assistant/main::voice"
