name    = "ai_voice_assistant"
version = "0.1.0"

[dependencies]
std      = "0.10.3"
http     = "0.10.3"
net      = "0.10.3"
encoding = "0.10.3"
fs       = "0.10.3"
record   = "0.10.3"
ml       = "0.10.3"

[entrypoints]
chat  = "ai_voice_assistant/main::chat"
voice = "ai_voice_assistant/main::voice"
