
use core/fs/direct::FileReader
use core/fs/direct::ReadFile
use core/fs/direct::FileWriter
use core/fs/direct::WriteFile
use core/text::DecodeBytes
use core/conversion::StringToByte

sequence Main()
  model FileReader(path="/tmp/tests/input_utf-8.txt")
  model FileWriter(path="/tmp/tests/output_for_input_utf-8.txt")
{
    ReadFile[reader=FileReader]()
    DecodeBytes()
    StringToByte()
    WriteFile[writer=FileWriter]()
    
    ReadFile.data -> DecodeBytes.data,value -> StringToByte.value,data -> WriteFile.data
}




