
include:
  - local: /.gitlab/ci/builds.yml
  - local: /.gitlab/ci/checks.yml
  - local: /.gitlab/ci/tests.yml
  - local: /.gitlab/ci/docs.yml
  - local: /.gitlab/ci/packaging.yml
  - local: /.gitlab/ci/releases.yml

variables:
  PACKAGES: work distrib encoding fs http javascript json net process regex sql std 

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

stages:
  - build
  - melodium
  - test
  - doc
  - packaging
  - release

melodium:melodium_gitlab:
  stage: melodium
  needs: []
  rules:
    - if: '$MELODIUM == "true"'
  image:
    name: registry.gitlab.com/melodium/melodium:alpine-0.9.0-pre.1
    entrypoint: [""]
  variables:
    MELODIUM_HOME: /melodium_home
  script:
    - /melodium run .melodium/Compo.toml main --on_gitlab=true --test=true --out_directory="\"$CI_PROJECT_DIR/results\"" --key "\"$MELODIUM_SERVICE_KEY\"" --repository_url "\"$CI_REPOSITORY_URL\"" --ci_token "\"$API_TOKEN\"" --project_id "\"$CI_PROJECT_ID\"" --sha "\"$CI_COMMIT_SHA\"" --ref "\"$CI_COMMIT_REF_NAME\"" --pipeline "\"$CI_PIPELINE_ID\""
  artifacts:
    paths:
      - $CI_PROJECT_DIR/results
    expire_in: 20 days
