
include:
  - local: /.gitlab/ci/builds.yml
  - local: /.gitlab/ci/checks.yml
  - local: /.gitlab/ci/libs.yml
  - local: /.gitlab/ci/tests.yml
  - local: /.gitlab/ci/docs.yml
  - local: /.gitlab/ci/packaging.yml
  - local: /.gitlab/ci/releases.yml

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

stages:
  - build
  - test
  - doc
  - packaging
  - release
