[package]
name = "melodium-rust"
version = "0.1.0"
authors = ["Quentin VIGNAUD <qvignaud@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1"
intertrait = "0.2"
linkme = "0.2"
async-std = "1.9.0"
