[workspace]
members = [
    "core-mel",
    "libs/conv-mel",
    "libs/flow-mel",
    "libs/ops-mel",
    "melodium",
    "melodium-common",
    "melodium-core",
    "melodium-doc",
    "melodium-engine",
    "melodium-lang",
    "melodium-lib",
    "melodium-loader",
    "melodium-macro",
    ]
