[workspace]
resolver = "2"
members = [
    "libs/encoding-mel",
    "libs/fs-mel",
    "libs/http-mel",
    "libs/javascript-mel",
    "libs/json-mel",
    "libs/process-mel",
    "libs/regex-mel",
    "libs/sql-mel",
    "libs/std-mel",
    "melodium",
    "melodium-common",
    "melodium-core",
    "melodium-doc",
    "melodium-engine",
    "melodium-lang",
    "melodium-lib",
    "melodium-loader",
    "melodium-macro",
    "melodium-repository",
    ]
exclude = [
    "tests/*"
    ]

[profile.release]
strip = true
