[workspace]
resolver = "2"
members = [
    "libs/conv-mel",
    "libs/engine-mel",
    "libs/flow-mel",
    "libs/fs-mel",
    "libs/ops-mel",
    "libs/regex-mel",
    "libs/text-mel",
    "libs/type-mel",
    "melodium",
    "melodium-common",
    "melodium-core",
    "melodium-doc",
    "melodium-engine",
    "melodium-lang",
    "melodium-lib",
    "melodium-loader",
    "melodium-macro",
    "melodium-repository",
    ]

[profile.release]
strip = true
