[package]
name = "melodium"
version = "0.2.1"
authors = ["Quentin VIGNAUD <qvignaud@gmail.com>"]
rust-version = "1.60"
edition = "2018"
license = "EUPL-1.2"
homepage = "https://melodium.tech"
repository = "https://gitlab.com/melodium/melodium"
readme = "README.md"
description = "Dataflow-oriented language & tool, focusing on treatments applied on data, allowing high scalability and massive parallelization safely."
keywords = ["dataflow","parallelization","scalability","async","signal"]
categories = ["compilers", "science", "concurrency", "asynchronous"]
exclude = [
    "melodium-tests/*",
    "examples/*",
    "utils/*"
]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.11.0"
futures = "0.3.21"
downcast-rs = "1.2.0"
lazy_static = "1.4.0"
itertools = "0.10.3"
linkme = "0.2.10"
regex = "1.5.5"
clap = { version = "3.1.12", features = ["cargo"] }
colored = "2.0.0"
encoding_rs = "0.8.31"
cpal = "0.13.5"
hound = "3.4.0"
glob = "0.3.0"

