[workspace]
members = [
    "core-mel",
    "melodium",
    "melodium-common",
    "melodium-core",
    "melodium-doc",
    "melodium-engine",
    "melodium-lang",
    "melodium-loader",
    "melodium-macro",
    "ops-mel",
    ]
