[package]
name = "melodium"
version = "0.1.0"
authors = ["Quentin VIGNAUD <qvignaud@gmail.com>"]
edition = "2018"
license = "EUPL-1.2"
homepage = "https://melodium.tech"
repository = "https://gitlab.com/melodium/melodium"
readme = "README.md"
description = "Dataflow-oriented language & tool, focusing on treatments applied on data, allowing high scalability and massive parallelization safely."
keywords = ["dataflow","parallelization","scalability","async","signal"]
categories = ["compilers", "science", "concurrency", "asynchronous"]
exclude = [
    "melodium-tests/*",
    "examples/*",
    "utils/*"
]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.9.0"
futures = "0.3"
downcast-rs = "1.2.0"
lazy_static = "1.4.0"
linkme = "0.2"
regex = "1"
clap = "2"
colored = "2"
encoding_rs = "0.8"
cpal = "0.13"
hound = "3.4"

