[package]
name = "melodium-rust"
version = "0.1.0"
authors = ["Quentin VIGNAUD <qvignaud@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.9.0"
futures = "0.3"
downcast-rs = "1.2.0"
lazy_static = "1.4.0"
linkme = "0.2"
regex = "1"
clap = "2"


