name    = "javascript_transform"
version = "0.1.0"

[dependencies]
std        = "0.10.2"
fs         = "0.10.2"
json       = "0.10.2"
javascript = "0.10.2"

[entrypoints]
main = "javascript_transform/main::main"
