name    = "javascript_transform"
version = "0.1.0"

[dependencies]
std        = "0.10.4"
fs         = "0.10.4"
json       = "0.10.4"
javascript = "0.10.4"

[entrypoints]
main = "javascript_transform/main::main"
