name    = "javascript_transform"
version = "0.1.0"

[dependencies]
std        = "0.10.3"
http       = "0.10.3"
net        = "0.10.3"
json       = "0.10.3"
encoding   = "0.10.3"
javascript = "0.10.3"

[entrypoints]
main = "javascript_transform/main::main"
