name = "melodium_ci"
version = "0.1.0"

[dependencies]
std = "0.9.1"
log = "0.9.1"
fs = "0.9.1"
process = "0.9.1"
work = "0.9.1"
distrib = "0.9.1"
net = "0.9.1"
cicd = "0.9.1"

http = "0.9.1"
json = "0.9.1"

[entrypoints]
main = "melodium_ci::main"
main_gitlab = "melodium_ci::mainGitlab"
