name = "melodium_ci"
version = "0.1.0"

[dependencies]
std = "0.9.0"
log = "0.9.0"
fs = "0.9.0"
process = "0.9.0"
work = "0.9.0"
distrib = "0.9.0"
net = "0.9.0"
cicd = "0.9.0"

http = "0.9.0"
json = "0.9.0"

[entrypoints]
main = "melodium_ci::main"
main_gitlab = "melodium_ci::mainGitlab"
