name = "melodium_ci"
version = "0.1.0"

[dependencies]
std = "=0.9.0-pre.2"
log = "=0.9.0-pre.2"
fs = "=0.9.0-pre.2"
process = "=0.9.0-pre.2"
work = "=0.9.0-pre.2"
distrib = "=0.9.0-pre.2"
net = "=0.9.0-pre.2"
cicd = "=0.9.0-pre.2"

http = "=0.9.0-pre.2"
json = "=0.9.0-pre.2"

[entrypoints]
main = "melodium_ci::main"
main_gitlab = "melodium_ci::mainGitlab"
