
use core/fs/direct::FileWriter
use core/fs/direct::WriteFile
use core/generation::ScalarI32Generator
use core/generation::GenerateScalarI32
use core/conversion/scalar::I32ToByte

sequence Main()
  model Generator: ScalarI32Generator(length=1024, value=-42)
  model File: FileWriter(path="generated_i32.mel_generation")
{
    Generate: GenerateScalarI32[generator=Generator]()
    Convert: I32ToByte()
    Write: WriteFile[writer=File]()
    
    Generate.data -> Convert.value,data -> Write.data
}


