
use std/fs/mono::WriteFile
use std/generation/scalar/i64::Generate
use std/conversion/scalar/i64::ToByte
use std/process/engine::ProcessReady
use std/process/engine::ProcessEnd
use std/flow/byte::Linearize
use std/flow/byte::Trigger

sequence Main()
{
    ProcessReady()
    ProcessEnd()
    Trigger()
    Generate(length=1024, value=-42)
    ToByte()
    Linearize()
    WriteFile(path="generated_i64.mel_generation")
    
    ProcessReady.trigger -> Generate.trigger,value -> ToByte.value,data -> Linearize.vector,value -> WriteFile.data
    Linearize.value -> Trigger.value,finish -> ProcessEnd.end
}


