
use std/fs/write/mono::WritePath
use std/generation/scalar/f64::Generate
use std/conversion/scalar/f64::ToByte
use std/process/engine::Ready
use std/flow/byte::Linearize
use std/flow/byte::Trigger

sequence Main()
{
    Ready()
    Generate(length=1024, value=-1234.56789123456789)
    ToByte()
    Linearize()
    WritePath(path="generated_f64.mel_generation")
    
    Ready.ready -> Generate.trigger,value -> ToByte.value,data -> Linearize.vector,value -> WritePath.data
}


