
use core/fs/direct::FileWriter
use core/fs/direct::WriteFile
use core/generation::ScalarU32Generator
use core/generation::GenerateScalarU32
use core/conversion/scalar::U32ToByte

sequence Main()
  model Generator: ScalarU32Generator(length=1024, value=42)
  model File: FileWriter(path="/tmp/tests/generated_u32.mel_generation")
{
    Generate: GenerateScalarU32[generator=Generator]()
    Convert: U32ToByte()
    Write: WriteFile[writer=File]()
    
    Generate.data -> Convert.value,data -> Write.data
}


