
use std/fs/write/mono::WritePath
use std/generation/scalar/i32::Generate
use std/conversion/scalar/i32::ToByte
use std/process/engine::ProcessReady
use std/process/engine::ProcessEnd
use std/flow/byte::Linearize
use std/flow/byte::Trigger

sequence Main()
{
    ProcessReady()
    ProcessEnd()
    Trigger()
    Generate(length=1024, value=-42)
    ToByte()
    Linearize()
    WritePath(path="generated_i32.mel_generation")
    
    ProcessReady.trigger -> Generate.trigger,value -> ToByte.value,data -> Linearize.vector,value -> WritePath.data
    Linearize.value -> Trigger.value,finish -> ProcessEnd.end
}


