
use core/fs/direct::FileWriter
use core/fs/direct::WriteFile
use core/generation::ScalarI8Generator
use core/generation::GenerateScalarI8
use core/conversion/scalar::I8ToByte

sequence Main()
  model Generator: ScalarI8Generator(length=1024, value=-42)
  model File: FileWriter(path="/tmp/tests/generated_i8.mel_generation")
{
    Generate: GenerateScalarI8[generator=Generator]()
    Convert: I8ToByte()
    Write: WriteFile[writer=File]()
    
    Generate.data -> Convert.value,data -> Write.data
}


