
use std/fs/write/mono::WritePath
use std/generation/scalar/char::Generate
use std/conversion/scalar/char::ToByte
use std/process/engine::Ready
use std/flow/byte::Linearize
use std/flow/byte::Trigger

sequence Main()
{
    Ready()
    Generate(length=1024, value=42)
    ToByte()
    Linearize()
    WritePath(path="generated_char.mel_generation")
    
    Ready.ready -> Generate.trigger,value -> ToByte.value,data -> Linearize.vector,value -> WritePath.data
}


