
use core/fs/direct::FileWriter
use core/fs/direct::WriteFile
use core/generation::ScalarU64Generator
use core/generation::GenerateScalarU64
use core/conversion/scalar::U64ToByte

sequence Main()
  model Generator: ScalarU64Generator(length=1024, value=42)
  model File: FileWriter(path="/tmp/tests/generated_u64.mel_generation")
{
    Generate: GenerateScalarU64[generator=Generator]()
    Convert: U64ToByte()
    Write: WriteFile[writer=File]()
    
    Generate.data -> Convert.value,data -> Write.data
}


