
use std/fs/mono::WriteFile
use std/generation/scalar/i8::Generate
use std/conversion/scalar/i8::ToByte
use std/process/engine::ProcessReady
use std/process/engine::ProcessEnd
use std/flow/byte::Trigger

sequence Main()
{
    ProcessReady()
    ProcessEnd()
    Trigger()
    Generate(length=1024, value=-42)
    ToByte()
    WriteFile(path="generated_i8.mel_generation")
    
    ProcessReady.trigger -> Generate.trigger,value -> ToByte.value,data -> WriteFile.data
    ToByte.data -> Trigger.value,finish -> ProcessEnd.end
}


