
use std/fs/mono/write::WritePath
use std/generation/scalar/i64::Generate
use std/conversion/scalar/i64::ToByte
use std/process/engine::Ready
use std/flow/byte::Linearize
use std/flow/byte::Trigger

sequence Main()
{
    Ready()
    Generate(length=1024, value=-42)
    ToByte()
    Linearize()
    WritePath(path="generated_i64.mel_generation")
    
    Ready.ready -> Generate.trigger,value -> ToByte.value,data -> Linearize.vector,value -> WritePath.data
}


