
use core/fs/direct::FileWriter
use core/fs/direct::WriteFile
use core/generation::ScalarU128Generator
use core/generation::GenerateScalarU128
use core/conversion/scalar::U128ToByte

sequence Main()
  model Generator: ScalarU128Generator(length=1024, value=42)
  model File: FileWriter(path="/tmp/tests/generated_u128.mel_generation")
{
    Generate: GenerateScalarU128[generator=Generator]()
    Convert: U128ToByte()
    Write: WriteFile[writer=File]()
    
    Generate.data -> Convert.value,data -> Write.data
}


