
use core/fs/direct::FileWriter
use core/fs/direct::WriteFile
use core/generation::ScalarI128Generator
use core/generation::GenerateScalarI128
use core/conversion/scalar::I128ToByte

sequence Main()
  model Generator: ScalarI128Generator(length=1024, value=-42)
  model File: FileWriter(path="/tmp/tests/generated_i128.mel_generation")
{
    Generate: GenerateScalarI128[generator=Generator]()
    Convert: I128ToByte()
    Write: WriteFile[writer=File]()
    
    Generate.data -> Convert.value,data -> Write.data
}


