#!/usr/bin/env melodium
#! name = fs_test
#! version = 0.8.0
#! require = std:0.8.0
#! require = fs:0.8.0

use std/engine/util::startup
use std/flow::generate
use std/flow::count
use std/conv::toBytes
use std/flow/vec::flatten
use std/flow::emit
use fs/local::writeLocal

treatment main() {
    
    startup()
    emitLength: emit<u128>(value=128000)
    generate<void>(data = _)
    
    startup.trigger -> emitLength.trigger,emit -> generate.length
    
    count<void>()
    toBytes<u128>()
    flatten<byte>()
    
    generate.stream -> count.stream,count -> toBytes.value,data -> flatten.vector
    
    writeLocal(path="./fs_try.data")
    
    flatten.value -> writeLocal.data
    
}
