#!/usr/bin/env melodium
#! name = generics
#! version = 0.8.0
#! require = std:0.8.0-rc2
#! require = fs:0.8.0-rc2

use std/flow::emit
use std/flow::trigger
use std/flow::stream
use fs/file::write
use std/engine/util::startup
use std/conv::toBytes
use std/flow/vec::flatten

/*
    This script is not supposed to do anything at this point, only to be parsed.
*/

treatment main() {
    
    make_stream<Vec<Vec<Vec<Option<u16>>>>>(my_value = [[[_]]], something = "Hey")
    trigger<Vec<Vec<Vec<Option<u16>>>>>()
    write_file()

  make_stream.values -> trigger.stream,end -> write_file.trigger
}

treatment make_stream<T: Vec>(var my_value: T, var something: string)
  output values: Stream<T>
{
  startup()
  emit<T>(value = my_value)
  nothing: emit<string>(value = something)
  stream<T>()

  startup.trigger -> emit.trigger,emit -> stream.block,stream -> Self.values
}

treatment write_file()
  input trigger: Block<void>
{
  emit<string>(value="Okey !")
  stream<string>()
  Self.trigger -> emit.trigger

  emit_filename: emit<string>(value="something.txt")
  Self.trigger -> emit_filename.trigger

  emit_filename.emit -> write.path

  toBytes<string>()
  flatten<byte>()
  write()

  emit.emit -> stream.block,stream -> toBytes.value,data -> flatten.vector,value -> write.data
}
