#!/usr/bin/env melodium
#! name = http_secrets_server
#! version = 0.1.0
#! require = std:0.11.0 http:0.11.0 net:0.11.0 encoding:0.11.0

use std/engine/util::startup
use std/engine/log::logInfo
use std/engine/log::logInfos
use std/data/string_map::get
use std/ops/option::unwrapOr
use std/flow::emit
use std/flow::stream
use std/data/string_map::StringMap
use std/data/string_map::|map
use std/ops/option/block::unwrap
use std/secret::reveal
use http/server::HttpServer
use http/server::start
use http/server::connection
use http/server::@HttpRequest
use http/method::|get
use http/status::|ok
use http/status::HttpStatus
use net/ip::|localhost_ipv4
use net/ip::|from_ipv4
use encoding::encode

treatment main(const port: u16)
  model server: HttpServer(host=|from_ipv4(|localhost_ipv4()), port=port)
{
    startup()
    start[http_server=server]()
    startup.trigger -> start.trigger

    check[http_server=server]()
}

treatment check[http_server: HttpServer]() {
    connection[http_server=http_server](method=|get(), route="/check")

    status:  emit<HttpStatus>(value=|ok())
    headers: emit<StringMap>(value=|map([]))
    connection.started -> status.trigger,emit  -> connection.status
    connection.started -> headers.trigger,emit -> connection.headers

    reply:   emit<string>(value="checked")
    asBytes: stream<string>()
    encoded: encode()
    connection.started -> reply.trigger,emit -> asBytes.block,stream -> encoded.text,data -> connection.data

    authorization()
    connection.started -> authorization.trigger

    // Headers given in plain.
    headersStream: stream<StringMap>()
    connection.headers -> headersStream.block
    plainClient: get(key="X-Client")
    plainAuthorization: get(key="Authorization")
    clientOrAbsent: unwrapOr<string>(default="absent")
    authorizationOrAbsent: unwrapOr<string>(default="absent")
    logClient: logInfos(label="plain x-client")
    logAuthorization: logInfos(label="plain authorization")
    headersStream.stream -> plainClient.map,value -> clientOrAbsent.option,value -> logClient.messages
    headersStream.stream -> plainAuthorization.map,value -> authorizationOrAbsent.option,value -> logAuthorization.messages
}

// Reveals the `Authorization` header of the request, given as a secret.
treatment authorization()
  require @HttpRequest
  input trigger: Block<void>
{
    emitAuth: emit<Option<Secret<string>>>(value=@HttpRequest[authorization])
    unwrapAuth: unwrap<Secret<string>>()
    revealAuth: reveal<string>()
    logAuth: logInfo(label="authorization")
    Self.trigger -> emitAuth.trigger,emit -> unwrapAuth.option,value -> revealAuth.secret,value -> logAuth.message
}
