#!/usr/bin/env melodium
#! name = http_client
#! version = 0.8.0
#! require = http:=0.8.0 std:=0.8.0 fs:=0.8.0

use http/client/util::get
use std/engine/util::startup
use fs/local::writeLocal
use fs/local::writeTextLocal
use std/text/convert/string::toUtf8
use std/flow::stream
use std/data::Map
use std/data::|map

treatment main(url: string, file: string, log: string)
{
    startup()
    get(url=url)
    writeLocal(path=file)

    startup.trigger -> get.trigger

    log: writeTextLocal(path=log)
    stream<string>()

    get.data ---------------------------> writeLocal.data
    get.error -> stream.block,stream ---> log.text
}

