#!/usr/bin/env melodium
#! name = http_client
#! version = 0.7.1
#! require = http:0.7.1 std:0.7.1 fs:0.7.1

use http/client::HttpClient
use http/client::get
use std/flow::emit
use std/engine/util::startup
use fs/file::write
use std/text/convert/string::toUtf8
use std/flow::stream

treatment main(url: string, file: string, log: string)
  model client: HttpClient(
    base_url= _
  )
{
    startup()
    url: emit<string>(value=url)
    filename: emit<string>(value=file)
    get[client=client]()
    write()

    startup.trigger -> url.trigger,emit -> get.url
    startup.trigger -> filename.trigger,emit -> write.path

    log_name: emit<string>(value=log)
    log: write()
    startup.trigger -> log_name.trigger,emit -> log.path
    toUtf8()
    stream<string>()

    get.data -> write.data
    get.failure -> stream.block,stream -> toUtf8.text,encoded -> log.data
}

