#!/usr/bin/env melodium
#! name = http_client
#! version = 0.9.0-pre.1
#! require = http:=0.9.0-pre.1 std:=0.9.0-pre.1 fs:=0.9.0-pre.1

use http/client/util::get
use std/engine/util::startup
use fs/local::writeLocal
use fs/local::writeTextLocal
use std/text/convert/string::toUtf8
use std/flow::stream

treatment main(url: string, file: string, log: string)
{
    startup()
    get(url=url)
    writeLocal(path=file)

    startup.trigger -> get.trigger

    log: writeTextLocal(path=log)
    stream<string>()

    get.data ---------------------------> writeLocal.data
    get.error -> stream.block,stream ---> log.text
}

