#!/usr/bin/env melodium
#! name = http_secrets_client
#! version = 0.1.0
#! require = std:0.11.0 http:0.11.0

use std/engine/util::startup
use std/engine/log::logError
use std/flow::emit
use std/data/map::Map
use std/data/map::|map as |secret_map
use std/data/map::|entry as |secret_entry
use std/data/string_map::StringMap
use std/data/string_map::|map
use std/data/string_map::|entry
use std/ops/option::|wrap
use std/secret::|format as |secret_format
use std/secret::|from_environment
use http/client::HttpClient
use http/client::get

treatment main(const url: string)
  model client: HttpClient(
      base_url=_,
      headers=|map([|entry("X-Client", "secret-test")]),
      secret_headers=|wrap<Map>(|secret_map([
          |secret_entry<Secret<string>>("Authorization", |secret_format(
              "Bearer {token}",
              |secret_map([|secret_entry<Secret<string>>("token", |from_environment("MELODIUM_SECRET_HTTP_TEST_TOKEN", "token"))]),
              "authorization"
          ))
      ]))
  )
{
    startup()
    emitUrl: emit<string>(value=url)
    noHeaders: emit<StringMap>(value=|map([]))
    request: get[client=client]()
    startup.trigger -> emitUrl.trigger,emit -> request.url
    startup.trigger -> noHeaders.trigger,emit -> request.headers
    logRequestError: logError(label="request")
    request.error -> logRequestError.message
}
