#!/usr/bin/env melodium
#! name = sleeper
#! version = 0.11.0
#! require = std:0.11.0 process:0.11.0

use std/engine/util::startup
use process/command::|command
use process/local::execOnce

// Runs `sleep <duration>` as child process, the duration identifying it.
treatment main(const duration: string)
{
    startup()
    sleep: execOnce(command=|command("sleep", [duration]))

    startup.trigger -> sleep.launch
}
