#!/usr/bin/env melodium
#! name = pull_secret
#! version = 0.1.0
#! require = std:0.11.0 work:0.11.0

use std/engine/util::startup
use std/engine/log::logErrors
use std/ops/option::|wrap
use std/secret::|from_environment
use work/distant::DistantEngine
use work/distant::distant
use work/resources::|container
use work/resources/arch::|amd64

treatment main(const api_url: string)
  model engine: DistantEngine(location="api", api_url=|wrap<string>(api_url), api_token="env:MELODIUM_SECRET_PULL_TEST_API_TOKEN")
{
    startup()
    request: distant[distant_engine=engine](
        max_duration=60, memory=100, cpu=100, storage=100, edition=_, arch=_, volumes=[], tags=[],
        containers=[|container("main", 100, 100, 100, |amd64(), [], "alpine", |wrap<Secret<string>>(|from_environment("MELODIUM_SECRET_PULL_TEST_SECRET", "pull_secret")))],
        service_containers=[]
    )
    startup.trigger -> request.trigger
    logRequestErrors: logErrors(label="distant")
    request.errors -> logRequestErrors.messages
}
