#!/usr/bin/env melodium
#! name = regex_test
#! version = 0.9.0-pre.1
#! require = std:=0.9.0-pre.1
#! require = regex:=0.9.0-pre.1
#! require = fs:=0.9.0-pre.1

use std/engine/util::startup
use std/flow::emit
use std/flow::stream
use std/ops/option::unwrap
use std/data::Map
use std/data::get
use regex::capture
use fs/local::writeTextLocal

treatment main(text: string, file: string) {
    
    startup()
    emit<string>(value=text)
    stream<string>()
    capture(regex="(?<number>\\d+)")
    unwrapMap: unwrap<Map>()
    get<string>(key="number")
    unwrapString: unwrap<string>()
    writeTextLocal(path=file)

    startup.trigger -> emit.trigger,emit -> stream.block,stream -> capture.text,captured -> unwrapMap.option,value -> get.map,value -> unwrapString.option,value -> writeTextLocal.text
    
}
