#!/usr/bin/env melodium
#! name = secret_environment
#! version = 0.1.0
#! require = std:0.11.0 net:0.11.0 work:0.11.0 distrib:0.11.0 process:0.11.0

use std/engine/util::startup
use std/engine/log::logError
use std/flow::emit
use std/data/map::|map as |secret_map
use std/data/map::|entry as |secret_entry
use std/data/string_map::|map
use std/ops/option::|wrap
use std/ops/option::|unwrap_or
use std/ops/option/block::unwrap
use std/secret::|locate
use std/secret::|from_environment
use net/ip::|localhost_ipv4
use net/ip::|from_ipv4
use work/access::Access
use work/access::|new_access
use distrib::DistributionEngine
use distrib::start
use distrib::distribute
use distrib::sendBlock
use distrib::recvBlock
use process/command::Command
use process/command::|command
use process/environment::Environment
use process/environment::|environment
use process/environment::|with_secret_variables
use process/environment::|with_secret_stdin
use process/exec::Executor
use process/exec::execOne
use process/local::|local_executor

model Runner() : DistributionEngine {
    treatment = "secret_environment::run"
    version   = "0.1.0"
}

treatment main(
    const port: u16,
    const send_key: Secret<string> = "env:MELODIUM_SECRET_DIST_SEND_KEY",
    const recv_key: Secret<string> = "env:MELODIUM_SECRET_DIST_RECV_KEY",
    const directory: string,
    const transmission: string = "value"
)
  model distributor: Runner()
{
    startup()
    accessBlock: emit<Access>(value=|new_access([|from_ipv4(|localhost_ipv4())], port, send_key, recv_key))
    startup.trigger -> accessBlock.trigger

    distribStart: start[distributor=distributor](params=|secret_map([|secret_entry<string>("directory", directory)]))
    accessBlock.emit -> distribStart.access
    logStartError: logError(label="start")
    distribStart.error -> logStartError.message

    dist: distribute[distributor=distributor]()
    distribStart.ready -> dist.trigger

    sendTrigger: sendBlock<void>[distributor=distributor](name="trigger")
    dist.distribution_id -> sendTrigger.distribution_id
    distribStart.ready -> sendTrigger.data

    emitEnvironment: emit<Option<Environment>>(value=|wrap<Environment>(|with_secret_stdin(
        |with_secret_variables(
            |environment(|map([]), _, false, false),
            |secret_map([|secret_entry<Secret<string>>("TOKEN", |unwrap_or<Secret<string>>(
                |locate<string>("env:MELODIUM_SECRET_DIST_ENV_TOKEN", "token", transmission, false),
                |from_environment("MELODIUM_SECRET_DIST_ENV_TOKEN", "token")
            ))])
        ),
        |unwrap_or<Secret<string>>(
            |locate<string>("env:MELODIUM_SECRET_DIST_ENV_INPUT", "input", transmission, false),
            |from_environment("MELODIUM_SECRET_DIST_ENV_INPUT", "input")
        )
    )))
    sendEnvironment: sendBlock<Option<Environment>>[distributor=distributor](name="environment")
    dist.distribution_id -> sendEnvironment.distribution_id
    distribStart.ready -> emitEnvironment.trigger,emit -> sendEnvironment.data

    recvError: recvBlock<string>[distributor=distributor](name="error")
    dist.distribution_id -> recvError.distribution_id
    logRemoteError: logError(label="remote")
    recvError.data -> logRemoteError.message
}

// Executed by the distant engine: writes the `TOKEN` variable and the standard input to files.
treatment run(const directory: string)
  input  trigger:     Block<void>
  input  environment: Block<Option<Environment>>
  output error:       Block<string>
{
    emitExecutor: emit<Option<Executor>>(value=|local_executor())
    unwrapExecutor: unwrap<Executor>()
    emitCommand: emit<Command>(value=|command("sh", ["-c", "printf '%s' \"$TOKEN\" > \"$0/variable\"; cat > \"$0/input\"", directory]))
    execOne()

    Self.trigger -> emitExecutor.trigger,emit -> unwrapExecutor.option,value -> execOne.executor
    Self.trigger -> emitCommand.trigger,emit -> execOne.command
    Self.environment -> execOne.environment
    execOne.error -> Self.error
}
