name    = "ci_failure_triage"
version = "0.1.0"

[dependencies]
std        = "0.10.3"
process    = "0.10.3"
work       = "0.10.3"
cicd       = "0.10.3"
encoding   = "0.10.3"
json       = "0.10.3"
javascript = "0.10.3"
ml         = "0.10.3"
fs         = "0.10.3"

[entrypoints]
main = "ci_failure_triage/main::main"
