name    = "ci_failure_triage"
version = "0.1.0"

[dependencies]
std        = "0.10.4"
process    = "0.10.4"
work       = "0.10.4"
cicd       = "0.10.4"
encoding   = "0.10.4"
json       = "0.10.4"
javascript = "0.10.4"
ml         = "0.10.4"
fs         = "0.10.4"

[entrypoints]
main = "ci_failure_triage/main::main"
