
use conv/i64::toVoid
use flow/void::count as voidCount

/**
    Gives count of elements passing through input stream.

    This count increment one for each elements within the `iter` stream, starting at 1.
    
    ```mermaid
    graph LR
        T("count()")
        V["🟦 🟦 🟦…"] -->|iter| T
        
        T -->|count| P["1️⃣ 2️⃣ 3️⃣ …"]
    
        style V fill:#ffff,stroke:#ffff
        style P fill:#ffff,stroke:#ffff
    ```
*/
treatment count()
  input iter: Stream<i64>
  output count: Stream<u128>
{
    toVoid()
    voidCount()

    Self.iter -> toVoid.value,iter -> voidCount.iter,count -> Self.count
}

