
use core/text::DecodeBytes
use core/text::EncodeBytes

sequence Decode(var encoding: string = "utf-8")
    input data: Stream<byte>
    output text: Stream<string>
{
    DecodeBytes(encoding=encoding)

    Self.data -> DecodeBytes.data,value -> Self.text
}

sequence Encode(var encoding: string = "utf-8")
    input text: Stream<string>
    output data: Stream<byte>
{
    EncodeBytes(encoding=encoding)

    Self.text -> EncodeBytes.value,data -> Self.data
}


