[package]
name = "melodium"
version = "0.6.0"
authors = ["Quentin VIGNAUD <qvignaud@gmail.com>"]
rust-version = "1.60"
edition = "2018"
license = "EUPL-1.2"
homepage = "https://melodium.tech"
repository = "https://gitlab.com/melodium/melodium"
readme = "README.md"
description = "Dataflow-oriented language & tool, focusing on treatments applied on data, allowing high scalability and massive parallelization safely"
keywords = ["dataflow","parallelization","scalability","async","signal"]
categories = ["compilers", "science", "concurrency", "asynchronous"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "melodium"

[[bin]]
name = "melodium"
required-features = ["cli"]

[dependencies]
clap = { version = "4.0.9", features = ["cargo", "derive"], optional = true }
colored = { version = "2.0.0", optional = true }
melodium-common = { path = "../melodium-common", version = "0.6.0" }
melodium-engine = { path = "../melodium-engine", version = "0.6.0" }
melodium-loader = { path = "../melodium-loader", version = "0.6.0" }
melodium-doc = { path = "../melodium-doc", version = "0.6.0", optional = true }

conv-mel = { path = "../libs/conv-mel", version = "0.6.0", optional = true }
flow-mel = { path = "../libs/flow-mel", version = "0.6.0", optional = true }
fs-mel = { path = "../libs/fs-mel", version = "0.6.0", optional = true }
ops-mel = { path = "../libs/ops-mel", version = "0.6.0", optional = true }
type-mel = { path = "../libs/type-mel", version = "0.6.0", optional = true }

[features]
default = ["cli", "standard-edition"]
cli = ["clap", "colored"]
doc = ["melodium-doc"]
core = ["conv-mel", "flow-mel", "ops-mel", "type-mel"]
std = ["core", "fs-mel"]
standard-edition = ["std", "doc"]
