name    = "ci_pipeline"
version = "0.1.0"

[dependencies]
std     = "0.10.2"
fs      = "0.10.2"
process = "0.10.2"
work    = "0.10.2"
distrib = "0.10.2"
cicd    = "0.10.2"

[entrypoints]
main = "ci_pipeline/main::main"
