
use core/arithmetic/scalar/i32::|add
use std/fs/mono/write::WritePath
use std/process/engine::Ready
use std/flow/byte::Trigger
use std/generation/scalar/i32::Generate
use std/conversion/scalar/i32::ToString
use std/text/encoding::Encode

sequence Main()
{
    Ready()
    Trigger()
    Generate(length=1, value=|add(40, 2))
    ToString()
    Encode()
    WritePath(path="output.txt")
    
    Ready.ready -> Generate.trigger,value -> ToString.value,value -> Encode.text,data -> WritePath.data

}
