use crate::executive::Value;

use super::{Data, DataTrait};
use core::fmt::{Display, Formatter, Result};
use std::sync::Arc;

#[derive(Clone, Debug)]
pub enum DataType {
    /// Special variant not aimed to be explicitly used,
    /// it corresponds to the case a value Vec or Option
    /// didn't contain any data, so is not determinable.
    /// It always matches other data type, including itself.
    Undetermined,

    Void,

    I8,
    I16,
    I32,
    I64,
    I128,

    U8,
    U16,
    U32,
    U64,
    U128,

    F32,
    F64,

    Bool,
    Byte,

    Char,
    String,

    Vec(Box<DataType>),
    Option(Box<DataType>),

    Data(Arc<dyn Data>),
}

impl DataType {
    pub fn implements(&self, data_trait: &DataTrait) -> bool {
        match data_trait {
            DataTrait::Option => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => true,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Vec => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => true,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToI8 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToI16 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToI32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToI64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToI128 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToU8 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => true,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToU16 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToU32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToU64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToU128 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToF32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToF64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToBool => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToByte => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToChar => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => true,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToString => match self {
                DataType::Undetermined => false,
                DataType::Void => true,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToI8 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToI16 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToI32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToI64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToI128 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToU8 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToU16 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToU32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToU64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToU128 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToF32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToF64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToBool => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToByte => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToChar => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => true,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToString => match self {
                DataType::Undetermined => false,
                DataType::Void => true,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToI8 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToI16 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToI32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToI64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToI128 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToU8 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToU16 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToU32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToU64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToU128 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToF32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToF64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Bounded => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => true,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(_) => false,
            },
            DataTrait::Binary => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Signed => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Float => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::PartialEquality => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Equality => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::PartialOrder => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Order => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Add => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::CheckedAdd => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingAdd => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::WrappingAdd => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Sub => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::CheckedSub => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingSub => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::WrappingSub => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Mul => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::CheckedMul => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingMul => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::WrappingMul => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Div => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::CheckedDiv => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Rem => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::CheckedRem => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Neg => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::CheckedNeg => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::WrappingNeg => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Pow => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::CheckedPow => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Euclid => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::CheckedEuclid => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Hash => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(inner) => inner.implements(data_trait),
                DataType::Option(inner) => inner.implements(data_trait),
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Serialize => match self {
                DataType::Undetermined => false,
                DataType::Void => true,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(inner) => inner.implements(data_trait),
                DataType::Option(inner) => inner.implements(data_trait),
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Deserialize => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(inner) => inner.implements(data_trait),
                DataType::Option(inner) => inner.implements(data_trait),
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Display => match self {
                DataType::Undetermined => false,
                DataType::Void => true,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(inner) => inner.implements(data_trait),
                DataType::Option(inner) => inner.implements(data_trait),
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
        }
    }

    pub fn bounded_min(&self) -> Value {
        match self {
            DataType::I8 => Value::I8(i8::MIN),
            DataType::I16 => Value::I16(i16::MIN),
            DataType::I32 => Value::I32(i32::MIN),
            DataType::I64 => Value::I64(i64::MIN),
            DataType::I128 => Value::I128(i128::MIN),
            DataType::U8 => Value::U8(u8::MIN),
            DataType::U16 => Value::U16(u16::MIN),
            DataType::U32 => Value::U32(u32::MIN),
            DataType::U64 => Value::U64(u64::MIN),
            DataType::U128 => Value::U128(u128::MIN),
            DataType::F32 => Value::F32(f32::MIN),
            DataType::F64 => Value::F64(f64::MIN),
            DataType::Byte => Value::Byte(u8::MIN),
            _ => panic!("Bounded not supported for {}", self),
        }
    }

    pub fn bounded_max(&self) -> Value {
        match self {
            DataType::I8 => Value::I8(i8::MAX),
            DataType::I16 => Value::I16(i16::MAX),
            DataType::I32 => Value::I32(i32::MAX),
            DataType::I64 => Value::I64(i64::MAX),
            DataType::I128 => Value::I128(i128::MAX),
            DataType::U8 => Value::U8(u8::MAX),
            DataType::U16 => Value::U16(u16::MAX),
            DataType::U32 => Value::U32(u32::MAX),
            DataType::U64 => Value::U64(u64::MAX),
            DataType::U128 => Value::U128(u128::MAX),
            DataType::F32 => Value::F32(f32::MAX),
            DataType::F64 => Value::F64(f64::MAX),
            DataType::Byte => Value::Byte(u8::MAX),
            _ => panic!("Bounded not supported for {}", self),
        }
    }

    pub fn float_infinity(&self) -> Value {
        match self {
            DataType::F32 => Value::F32(f32::INFINITY),
            DataType::F64 => Value::F64(f64::INFINITY),
            _ => panic!("Float not supported for {}", self),
        }
    }

    pub fn float_neg_infinity(&self) -> Value {
        match self {
            DataType::F32 => Value::F32(f32::NEG_INFINITY),
            DataType::F64 => Value::F64(f64::NEG_INFINITY),
            _ => panic!("Float not supported for {}", self),
        }
    }

    pub fn float_nan(&self) -> Value {
        match self {
            DataType::F32 => Value::F32(f32::NAN),
            DataType::F64 => Value::F64(f64::NAN),
            _ => panic!("Float not supported for {}", self),
        }
    }
}

impl PartialEq for DataType {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::Vec(l0), Self::Vec(r0)) => l0 == r0,
            (Self::Option(l0), Self::Option(r0)) => l0 == r0,
            (Self::Data(l0), Self::Data(r0)) => l0.identifier() == r0.identifier(),
            (Self::Undetermined, _) | (_, Self::Undetermined) => true,
            _ => core::mem::discriminant(self) == core::mem::discriminant(other),
        }
    }
}

impl Display for DataType {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        match self {
            DataType::Undetermined => write!(f, "undetermined"),
            DataType::Void => write!(f, "void"),
            DataType::I8 => write!(f, "i8"),
            DataType::I16 => write!(f, "i16"),
            DataType::I32 => write!(f, "i32"),
            DataType::I64 => write!(f, "i64"),
            DataType::I128 => write!(f, "i128"),
            DataType::U8 => write!(f, "u8"),
            DataType::U16 => write!(f, "u16"),
            DataType::U32 => write!(f, "u32"),
            DataType::U64 => write!(f, "u64"),
            DataType::U128 => write!(f, "u128"),
            DataType::F32 => write!(f, "f32"),
            DataType::F64 => write!(f, "f64"),
            DataType::Bool => write!(f, "bool"),
            DataType::Byte => write!(f, "byte"),
            DataType::Char => write!(f, "char"),
            DataType::String => write!(f, "string"),
            DataType::Vec(dt) => write!(f, "Vec<{dt}>"),
            DataType::Option(dt) => write!(f, "Option<{dt}>"),
            DataType::Data(obj) => write!(f, "{}", obj.identifier().name()),
        }
    }
}
