use super::{Data, DataTrait};
use crate::executive::Value;
use core::fmt::{Display, Formatter, Result};
use erased_serde::Deserializer;
use std::sync::Arc;

#[derive(Clone, Debug)]
pub enum DataType {
    /// Special variant not aimed to be explicitly used,
    /// it corresponds to the case a value Vec or Option
    /// didn't contain any data, so is not determinable.
    /// It always matches other data type, including itself.
    Undetermined,

    Void,

    I8,
    I16,
    I32,
    I64,
    I128,

    U8,
    U16,
    U32,
    U64,
    U128,

    F32,
    F64,

    Bool,
    Byte,

    Char,
    String,

    Vec(Box<DataType>),
    Option(Box<DataType>),
    /// Sensitive value of the inner type, see `executive::Secret`.
    /// Implements no data trait except `Serialize` and `Deserialize`,
    /// which follow the inner type.
    Secret(Box<DataType>),

    Data(Arc<dyn Data>),
}

impl DataType {
    /// Tells if a secret appears at any depth of this type.
    pub fn contains_secret(&self) -> bool {
        match self {
            DataType::Secret(_) => true,
            DataType::Vec(inner) | DataType::Option(inner) => inner.contains_secret(),
            _ => false,
        }
    }

    pub fn implements(&self, data_trait: &DataTrait) -> bool {
        match data_trait {
            DataTrait::Option => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => true,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Vec => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => true,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToI8 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToI16 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToI32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToI64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToI128 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToU8 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => true,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToU16 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToU32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToU64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToU128 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToF32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToF64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToBool => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToByte => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToChar => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => true,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::ToString => match self {
                DataType::Undetermined => false,
                DataType::Void => true,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToI8 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToI16 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToI32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToI64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToI128 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToU8 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToU16 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToU32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToU64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToU128 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToF32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToF64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToBool => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToByte => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => true,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToChar => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => true,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::TryToString => match self {
                DataType::Undetermined => false,
                DataType::Void => true,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToI8 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToI16 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToI32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToI64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToI128 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToU8 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToU16 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToU32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToU64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToU128 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToF32 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingToF64 => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Bounded => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => true,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Binary => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Signed => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Float => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => false,
                DataType::I16 => false,
                DataType::I32 => false,
                DataType::I64 => false,
                DataType::I128 => false,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::PartialEquality => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Equality => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::PartialOrder => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Order => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Add => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::CheckedAdd => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingAdd => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::WrappingAdd => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Sub => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::CheckedSub => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingSub => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::WrappingSub => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Mul => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::CheckedMul => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::SaturatingMul => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::WrappingMul => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Div => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::CheckedDiv => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Rem => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::CheckedRem => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Neg => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::CheckedNeg => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::WrappingNeg => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => false,
                DataType::U16 => false,
                DataType::U32 => false,
                DataType::U64 => false,
                DataType::U128 => false,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Pow => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::CheckedPow => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Euclid => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::CheckedEuclid => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => false,
                DataType::Byte => false,
                DataType::Char => false,
                DataType::String => false,
                DataType::Vec(_) => false,
                DataType::Option(_) => false,
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Hash => match self {
                DataType::Undetermined => false,
                DataType::Void => false,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => false,
                DataType::F64 => false,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(inner) => inner.implements(data_trait),
                DataType::Option(inner) => inner.implements(data_trait),
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Serialize => match self {
                DataType::Undetermined => false,
                DataType::Void => true,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(inner) => inner.implements(data_trait),
                DataType::Option(inner) => inner.implements(data_trait),
                DataType::Secret(inner) => inner.implements(data_trait),
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Deserialize => match self {
                DataType::Undetermined => false,
                DataType::Void => true,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(inner) => inner.implements(data_trait),
                DataType::Option(inner) => inner.implements(data_trait),
                DataType::Secret(inner) => inner.implements(data_trait),
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
            DataTrait::Display => match self {
                DataType::Undetermined => false,
                DataType::Void => true,
                DataType::I8 => true,
                DataType::I16 => true,
                DataType::I32 => true,
                DataType::I64 => true,
                DataType::I128 => true,
                DataType::U8 => true,
                DataType::U16 => true,
                DataType::U32 => true,
                DataType::U64 => true,
                DataType::U128 => true,
                DataType::F32 => true,
                DataType::F64 => true,
                DataType::Bool => true,
                DataType::Byte => true,
                DataType::Char => true,
                DataType::String => true,
                DataType::Vec(inner) => inner.implements(data_trait),
                DataType::Option(inner) => inner.implements(data_trait),
                DataType::Secret(_) => false,
                DataType::Data(obj) => obj.implements().iter().any(|dt| dt == data_trait),
            },
        }
    }

    pub fn bounded_min(&self) -> Value {
        match self {
            DataType::I8 => Value::I8(i8::MIN),
            DataType::I16 => Value::I16(i16::MIN),
            DataType::I32 => Value::I32(i32::MIN),
            DataType::I64 => Value::I64(i64::MIN),
            DataType::I128 => Value::I128(i128::MIN),
            DataType::U8 => Value::U8(u8::MIN),
            DataType::U16 => Value::U16(u16::MIN),
            DataType::U32 => Value::U32(u32::MIN),
            DataType::U64 => Value::U64(u64::MIN),
            DataType::U128 => Value::U128(u128::MIN),
            DataType::F32 => Value::F32(f32::MIN),
            DataType::F64 => Value::F64(f64::MIN),
            DataType::Byte => Value::Byte(u8::MIN),
            DataType::Data(data) => data.bounded_min(),
            _ => panic!("Bounded not supported for {}", self),
        }
    }

    pub fn bounded_max(&self) -> Value {
        match self {
            DataType::I8 => Value::I8(i8::MAX),
            DataType::I16 => Value::I16(i16::MAX),
            DataType::I32 => Value::I32(i32::MAX),
            DataType::I64 => Value::I64(i64::MAX),
            DataType::I128 => Value::I128(i128::MAX),
            DataType::U8 => Value::U8(u8::MAX),
            DataType::U16 => Value::U16(u16::MAX),
            DataType::U32 => Value::U32(u32::MAX),
            DataType::U64 => Value::U64(u64::MAX),
            DataType::U128 => Value::U128(u128::MAX),
            DataType::F32 => Value::F32(f32::MAX),
            DataType::F64 => Value::F64(f64::MAX),
            DataType::Byte => Value::Byte(u8::MAX),
            DataType::Data(data) => data.bounded_max(),
            _ => panic!("Bounded not supported for {}", self),
        }
    }

    pub fn float_infinity(&self) -> Value {
        match self {
            DataType::F32 => Value::F32(f32::INFINITY),
            DataType::F64 => Value::F64(f64::INFINITY),
            DataType::Data(data) => data.float_infinity(),
            _ => panic!("Float not supported for {}", self),
        }
    }

    pub fn float_neg_infinity(&self) -> Value {
        match self {
            DataType::F32 => Value::F32(f32::NEG_INFINITY),
            DataType::F64 => Value::F64(f64::NEG_INFINITY),
            DataType::Data(data) => data.float_neg_infinity(),
            _ => panic!("Float not supported for {}", self),
        }
    }

    pub fn float_nan(&self) -> Value {
        match self {
            DataType::F32 => Value::F32(f32::NAN),
            DataType::F64 => Value::F64(f64::NAN),
            DataType::Data(data) => data.float_nan(),
            _ => panic!("Float not supported for {}", self),
        }
    }

    pub fn deserialize(
        &self,
        deserializer: &mut dyn Deserializer,
    ) -> std::result::Result<Value, erased_serde::Error> {
        // Secrets are never built from serialized content; a received secret goes
        // through the policy-aware conversion of the distribution layer instead.
        if self.contains_secret() {
            return Err(<erased_serde::Error as serde::de::Error>::custom(format!(
                "{self} cannot be deserialized"
            )));
        }

        Ok(match self {
            DataType::Void => Value::Void(erased_serde::deserialize(deserializer)?),
            DataType::I8 => Value::I8(erased_serde::deserialize(deserializer)?),
            DataType::I16 => Value::I16(erased_serde::deserialize(deserializer)?),
            DataType::I32 => Value::I32(erased_serde::deserialize(deserializer)?),
            DataType::I64 => Value::I64(erased_serde::deserialize(deserializer)?),
            DataType::I128 => Value::I128(erased_serde::deserialize(deserializer)?),
            DataType::U8 => Value::U8(erased_serde::deserialize(deserializer)?),
            DataType::U16 => Value::U16(erased_serde::deserialize(deserializer)?),
            DataType::U32 => Value::U32(erased_serde::deserialize(deserializer)?),
            DataType::U64 => Value::U64(erased_serde::deserialize(deserializer)?),
            DataType::U128 => Value::U128(erased_serde::deserialize(deserializer)?),
            DataType::F32 => Value::F32(erased_serde::deserialize(deserializer)?),
            DataType::F64 => Value::F64(erased_serde::deserialize(deserializer)?),
            DataType::Bool => Value::Bool(erased_serde::deserialize(deserializer)?),
            DataType::Byte => Value::Byte(erased_serde::deserialize(deserializer)?),
            DataType::Char => Value::Char(erased_serde::deserialize(deserializer)?),
            DataType::String => Value::String(erased_serde::deserialize(deserializer)?),
            DataType::Vec(data_type) => Value::Vec(
                (0..)
                    .map_while(|_| data_type.deserialize(deserializer).ok())
                    .collect(),
            ),
            DataType::Option(data_type) => {
                Value::Option(match data_type.deserialize(deserializer) {
                    Ok(value) => Some(Box::new(value)),
                    Err(_error) => None,
                })
            }
            DataType::Data(data) => data.deserialize(deserializer)?,
            _ => panic!("Deserialize not supported for {}", self),
        })
    }
}

impl PartialEq for DataType {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::Vec(l0), Self::Vec(r0)) => l0 == r0,
            (Self::Option(l0), Self::Option(r0)) => l0 == r0,
            (Self::Secret(l0), Self::Secret(r0)) => l0 == r0,
            (Self::Data(l0), Self::Data(r0)) => l0.identifier() == r0.identifier(),
            (Self::Undetermined, _) | (_, Self::Undetermined) => true,
            _ => core::mem::discriminant(self) == core::mem::discriminant(other),
        }
    }
}

impl Display for DataType {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        match self {
            DataType::Undetermined => write!(f, "undetermined"),
            DataType::Void => write!(f, "void"),
            DataType::I8 => write!(f, "i8"),
            DataType::I16 => write!(f, "i16"),
            DataType::I32 => write!(f, "i32"),
            DataType::I64 => write!(f, "i64"),
            DataType::I128 => write!(f, "i128"),
            DataType::U8 => write!(f, "u8"),
            DataType::U16 => write!(f, "u16"),
            DataType::U32 => write!(f, "u32"),
            DataType::U64 => write!(f, "u64"),
            DataType::U128 => write!(f, "u128"),
            DataType::F32 => write!(f, "f32"),
            DataType::F64 => write!(f, "f64"),
            DataType::Bool => write!(f, "bool"),
            DataType::Byte => write!(f, "byte"),
            DataType::Char => write!(f, "char"),
            DataType::String => write!(f, "string"),
            DataType::Vec(dt) => write!(f, "Vec<{dt}>"),
            DataType::Option(dt) => write!(f, "Option<{dt}>"),
            DataType::Secret(dt) => write!(f, "Secret<{dt}>"),
            DataType::Data(obj) => write!(f, "{}", obj.identifier().name()),
        }
    }
}

#[cfg(test)]
mod secret_tests {
    use super::*;
    use crate::descriptor::DescribedType;
    use serde::de::value::{Error as DeError, StrDeserializer};

    macro_rules! all_traits {
        ($($data_trait:ident),* $(,)?) => {
            const ALL_TRAITS: &[DataTrait] = &[$(DataTrait::$data_trait),*];

            // Fails to compile when a trait is added without being listed above.
            #[allow(dead_code)]
            fn all_traits_are_listed(data_trait: DataTrait) {
                match data_trait {
                    $(DataTrait::$data_trait)|* => {}
                }
            }
        };
    }

    all_traits!(
        Option,
        Vec,
        ToI8,
        ToI16,
        ToI32,
        ToI64,
        ToI128,
        ToU8,
        ToU16,
        ToU32,
        ToU64,
        ToU128,
        ToF32,
        ToF64,
        ToBool,
        ToByte,
        ToChar,
        ToString,
        TryToI8,
        TryToI16,
        TryToI32,
        TryToI64,
        TryToI128,
        TryToU8,
        TryToU16,
        TryToU32,
        TryToU64,
        TryToU128,
        TryToF32,
        TryToF64,
        TryToBool,
        TryToByte,
        TryToChar,
        TryToString,
        SaturatingToI8,
        SaturatingToI16,
        SaturatingToI32,
        SaturatingToI64,
        SaturatingToI128,
        SaturatingToU8,
        SaturatingToU16,
        SaturatingToU32,
        SaturatingToU64,
        SaturatingToU128,
        SaturatingToF32,
        SaturatingToF64,
        Bounded,
        Binary,
        Signed,
        Float,
        PartialEquality,
        Equality,
        PartialOrder,
        Order,
        Add,
        CheckedAdd,
        SaturatingAdd,
        WrappingAdd,
        Sub,
        CheckedSub,
        SaturatingSub,
        WrappingSub,
        Mul,
        CheckedMul,
        SaturatingMul,
        WrappingMul,
        Div,
        CheckedDiv,
        Rem,
        CheckedRem,
        Neg,
        CheckedNeg,
        WrappingNeg,
        Pow,
        CheckedPow,
        Euclid,
        CheckedEuclid,
        Hash,
        Serialize,
        Deserialize,
        Display,
    );

    fn inner_types() -> Vec<DataType> {
        vec![
            DataType::I64,
            DataType::F64,
            DataType::Bool,
            DataType::Byte,
            DataType::Char,
            DataType::String,
            DataType::Vec(Box::new(DataType::Byte)),
            DataType::Option(Box::new(DataType::String)),
        ]
    }

    fn secret_types(inner: &DataType) -> Vec<DataType> {
        let secret = DataType::Secret(Box::new(inner.clone()));
        vec![
            secret.clone(),
            DataType::Vec(Box::new(secret.clone())),
            DataType::Option(Box::new(secret.clone())),
            DataType::Vec(Box::new(DataType::Option(Box::new(secret)))),
        ]
    }

    /// `Vec` and `Option` traits describe the container itself, not its content,
    /// so a container of secrets keeps them.
    #[test]
    fn secrets_implement_no_trait_but_serialization() {
        for inner in inner_types() {
            for datatype in secret_types(&inner) {
                for data_trait in ALL_TRAITS {
                    let expected = match data_trait {
                        DataTrait::Serialize | DataTrait::Deserialize => {
                            inner.implements(data_trait)
                        }
                        DataTrait::Vec => matches!(datatype, DataType::Vec(_)),
                        DataTrait::Option => matches!(datatype, DataType::Option(_)),
                        _ => false,
                    };
                    assert_eq!(
                        datatype.implements(data_trait),
                        expected,
                        "{} for {}",
                        data_trait,
                        datatype
                    );
                    assert_eq!(
                        DescribedType::from(&datatype).implements(data_trait),
                        expected,
                        "{} for described {}",
                        data_trait,
                        datatype
                    );
                }
            }
        }
    }

    #[test]
    fn serialization_traits_follow_inner_type() {
        let not_serializable = DataType::Undetermined;
        assert!(!not_serializable.implements(&DataTrait::Serialize));
        let secret = DataType::Secret(Box::new(not_serializable));
        assert!(!secret.implements(&DataTrait::Serialize));
        assert!(!secret.implements(&DataTrait::Deserialize));
    }

    #[test]
    fn secret_type_equality_and_display() {
        let secret = DataType::Secret(Box::new(DataType::String));
        assert_eq!(secret, DataType::Secret(Box::new(DataType::String)));
        assert_ne!(secret, DataType::Secret(Box::new(DataType::Char)));
        assert_ne!(secret, DataType::String);
        assert_ne!(DataType::String, secret);
        assert_ne!(secret, DataType::Option(Box::new(DataType::String)));
        assert_eq!(secret.to_string(), "Secret<string>");
        assert_eq!(DescribedType::from(&secret).to_string(), "Secret<string>");
    }

    #[test]
    fn contains_secret_looks_through_containers() {
        assert!(!DataType::String.contains_secret());
        assert!(!DataType::Vec(Box::new(DataType::String)).contains_secret());
        for datatype in secret_types(&DataType::String) {
            assert!(datatype.contains_secret(), "{}", datatype);
        }
    }

    #[test]
    fn secrets_are_never_deserialized() {
        let mut deserializer =
            <dyn erased_serde::Deserializer>::erase(StrDeserializer::<DeError>::new("sentinel"));
        assert_eq!(
            DataType::String.deserialize(&mut deserializer).unwrap(),
            Value::String("sentinel".to_string())
        );

        for datatype in secret_types(&DataType::String) {
            let mut deserializer =
                <dyn erased_serde::Deserializer>::erase(StrDeserializer::<DeError>::new(
                    "sentinel",
                ));
            assert!(
                datatype.deserialize(&mut deserializer).is_err(),
                "{}",
                datatype
            );
        }
    }
}
