name    = "cloud_worker_pipeline"
version = "0.1.0"

[dependencies]
std        = "0.10.1"
fs         = "0.10.1"
encoding   = "0.10.1"
javascript = "0.10.1"
json       = "0.10.1"
work       = "0.10.1"
distrib    = "0.10.1"

[entrypoints]
main = "cloud_worker_pipeline/main::main"
