name    = "cloud_worker_pipeline"
version = "0.1.0"

[dependencies]
std        = "0.10.2"
fs         = "0.10.2"
encoding   = "0.10.2"
javascript = "0.10.2"
json       = "0.10.2"
work       = "0.10.2"
distrib    = "0.10.2"

[entrypoints]
main = "cloud_worker_pipeline/main::main"
