name    = "http_client"
version = "0.1.0"

[dependencies]
std      = "0.10.2"
http     = "0.10.2"
json     = "0.10.2"
encoding = "0.10.2"
fs       = "0.10.2"

[entrypoints]
main = "http_client/main::main"
