name    = "distributed_llm_cluster"
version = "0.1.0"

[dependencies]
std      = "0.10.3"
http     = "0.10.3"
net      = "0.10.3"
encoding = "0.10.3"
work     = "0.10.3"
distrib  = "0.10.3"
ml       = "0.10.3"

[entrypoints]
main = "distributed_llm_cluster/main::server"
