name    = "distributed_llm_cluster"
version = "0.1.0"

[dependencies]
std      = "0.10.4"
http     = "0.10.4"
net      = "0.10.4"
encoding = "0.10.4"
work     = "0.10.4"
distrib  = "0.10.4"
ml       = "0.10.4"

[entrypoints]
main = "distributed_llm_cluster/main::server"
