
use core/func::|add_i32
use std/fs/mono::WriteFile
use core/generation::ScalarI32Generator
use core/generation::GenerateScalarI32
use std/conversion/scalar/i32::ToString
use std/text/encoding::Encode

sequence Main()
  model Generator: ScalarI32Generator(length=1, value=|add_i32(40, 2))
{
    Generate: GenerateScalarI32[generator=Generator]()
    ToString()
    Encode()
    WriteFile(path="output.txt")
    
    Generate.data -> ToString.value,value -> Encode.text,data -> WriteFile.data
}
