
use core/arithmetic/scalar/i32::|add
use std/fs/mono::WriteFile
use std/process/engine::ProcessReady
use std/process/engine::ProcessSigterm
use std/process/engine::ProcessEnd
use std/flow/byte::Trigger
use std/generation/scalar/i32::Generate
use std/conversion/scalar/i32::ToString
use std/text/encoding::Encode

sequence Main()
{
    ProcessReady()
    ProcessEnd()
    Trigger()
    Generate(length=1, value=|add(40, 2))
    ToString()
    Encode()
    WriteFile(path="output.txt")
    
    ProcessReady.trigger -> Generate.trigger,value -> ToString.value,value -> Encode.text,data -> WriteFile.data
    Encode.data -> Trigger.value,finish -> ProcessEnd.end

}
