[package]
name = "record-mel"
version = "0.10.2"
authors = ["Quentin VIGNAUD <quentin.vignaud@melodium.tech>"]
rust-version = "1.83"
edition = "2021"
license = "EUPL-1.2"
homepage = "https://melodium.tech"
repository = "https://gitlab.com/melodium/melodium"
readme = "README.md"
description = "Mélodium recording processing library"
keywords = ["dataflow","parallelization","scalability","async","signal"]
categories = ["compilers", "science", "concurrency", "asynchronous"]

[lib]
crate-type = ["lib", "cdylib"]
name = "record_mel"

[dependencies]
async-std = "1.13"
async-channel = "2"
cpal = { version = "0.17", optional = true }
futures = "0.3.28"
melodium-core = { path = "../../melodium-core", version = "0.10.2" }
melodium-macro = { path = "../../melodium-macro", version = "0.10.2" }
std-mel = { path = "../std-mel", version = "0.10.2" }
audio-mel = { path = "../audio-mel", version = "0.10.2" }

[features]
mock = []
plugin = []
real = ["cpal"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

