name    = "http_json_pipeline"
version = "0.1.0"

[dependencies]
std      = "0.10.3"
http     = "0.10.3"
json     = "0.10.3"
fs       = "0.10.3"
encoding = "0.10.3"

[entrypoints]
main = "http_json_pipeline/main::main"
