
use std/fs/mono/read::ReadPath
use std/fs/mono/write::WritePath
use std/audio/encoding/wave::Decode
use std/audio/encoding/wave::Encode
use std/process/engine::Ready

sequence Main()
{
    Ready()
    RWi16: ReencodeWave(input="./input_i16.wav", output="./reencoded_i16.wav")
    RWi24: ReencodeWave(input="./input_i24.wav", output="./reencoded_i24.wav")
    RWf32: ReencodeWave(input="./input_f32.wav", output="./reencoded_f32.wav")

    Ready.ready -> RWi16.start
    Ready.ready -> RWi24.start
    Ready.ready -> RWf32.start
}

sequence ReencodeWave(const input: string, const output: string)
  input start: Block<void>
{
    ReadPath(path=input)
    Decode()
    Encode()
    WritePath(path=output)
    
    Self.start -> ReadPath.trigger,data -> Decode.data,mono -> Encode.signal,data -> WritePath.data
}

