
use std/fs/mono::ReadFile
use std/fs/mono::WriteFile
use std/audio/encoding/wave::Decode
use std/audio/encoding/wave::Encode

sequence Main()
{
    RWi16: ReencodeWave(input="./input_i16.wav", output="./reencoded_i16.wav")
    RWi24: ReencodeWave(input="./input_i24.wav", output="./reencoded_i24.wav")
    RWf32: ReencodeWave(input="./input_f32.wav", output="./reencoded_f32.wav")
}

sequence ReencodeWave(input: string, output: string)
{
    ReadFile(path=input)
    Decode()
    Encode()
    WriteFile(path=output)
    
    ReadFile.data -> Decode.data,mono -> Encode.signal,data -> WriteFile.data
}

