name    = "vision_chat"
version = "0.1.0"

[dependencies]
std        = "0.10.1"
fs         = "0.10.1"
http       = "0.10.1"
net        = "0.10.1"
json       = "0.10.1"
encoding   = "0.10.1"
javascript = "0.10.1"
ml         = "0.10.1"

[entrypoints]
main    = "vision_chat/main::main"
server  = "vision_chat/main::server"
