name    = "ci_pipeline"
version = "0.1.0"

[dependencies]
std     = "0.10.4"
fs      = "0.10.4"
process = "0.10.4"
work    = "0.10.4"
distrib = "0.10.4"
cicd    = "0.10.4"

[entrypoints]
main = "ci_pipeline/main::main"
