use std/flow/string::Linearize

use core/conversion/vector::StringToVoid

/**
Convert stream of `Vec<string>` into `Vec<void>` one.

This conversion is useful to extract pattern from a stream of vectors and work on it.

*/
sequence ToVoid()
  input  vector:  Stream<Vec<string>>
  output pattern: Stream<Vec<void>>
{
    StringToVoid()

    Self.vector -> StringToVoid.vector,pattern -> Self.pattern
}

