name    = "sql_crud_api"
version = "0.1.0"

[dependencies]
std      = "0.10.3"
http     = "0.10.3"
net      = "0.10.3"
sql      = "0.10.3"
encoding = "0.10.3"

[entrypoints]
main = "sql_crud_api/main::main"
