
use core/flow::StreamByteToBlockVecByte
use core/flow::BlockVecByteToStreamByte

sequence BlockBytes()
    input stream: Stream<byte>
    output block: Block<Vec<byte>>
{
    StreamByteToBlockVecByte()

    Self.stream -> StreamByteToBlockVecByte.data,data -> Self.block
}

sequence StreamBytes()
    input block: Block<Vec<byte>>
    output stream: Stream<byte>
{
    BlockVecByteToStreamByte()

    Self.block -> BlockVecByteToStreamByte.data,data -> Self.stream
}