
use core/text::DecodeBytes
use core/conversion/scalar::StringToByte

sequence Decode(var encoding: string = "utf-8")
    input data: Stream<byte>
    output text: Stream<string>
{
    DecodeBytes(encoding=encoding)

    Self.data -> DecodeBytes.data,value -> Self.text
}

sequence EncodeAsUtf8()
    input text: Stream<string>
    output data: Stream<byte>
{
    StringToByte()

    Self.text -> StringToByte.value,data -> Self.data
}
