
use std/fs/mono/write::WritePath
use std/generation/scalar/string::Generate
use std/conversion/scalar/string::ToByte
use std/process/engine::Ready
use std/flow/byte::Linearize
use std/flow/byte::Trigger

sequence Main()
{
    Ready()
    Generate(length=1024, value="Mélodium")
    ToByte()
    Linearize()
    WritePath(path="generated_string.mel_generation")
    
    Ready.ready -> Generate.trigger,value -> ToByte.value,data -> Linearize.vector,value -> WritePath.data
}


