name    = "sql_user_api"
version = "0.1.0"

[dependencies]
std  = "0.10.2"
http = "0.10.2"
net  = "0.10.2"
json = "0.10.2"
sql  = "0.10.2"
encoding = "0.10.2"

[entrypoints]
main = "sql_user_api/main::main"
