
use super::Builder;
use super::super::descriptor::CoreTreatmentDescriptor;
use super::super::super::executive::environment::{GenesisEnvironment, ContextualEnvironment};

/*#[derive(Debug)]
pub struct CoreTreatmentBuilder {

}

impl Builder for CoreTreatmentBuilder {

    fn static_build(&self, environment: &dyn GenesisEnvironment) {

    }

    fn dynamic_build(&self,  environment: &dyn ContextualEnvironment) {

    }
}*/

// Makes no sense to have generic builders for core elements: they should have their dedicated one generated by macros.

pub struct CoreTreatmentBuilder {

}
