
use std/process/engine::StandardInput
use std/process/engine::StandardOutput
use std/process/engine::ProcessEnd
use std/fs/write/mono::WritePath
use std/text/encoding::Encode
use std/flow/string::Trigger

sequence Write(const file: string)
    input text: Stream<string>
{

    Encode()
    WritePath(path=file)
    
    Self.text -> Encode.text,data -> WritePath.data
}

sequence Main()
{
    StandardInput()
    StandardOutput()
    Write(file="output.txt")

    Trigger()
    ProcessEnd()

    StandardInput.line -> StandardOutput.text
    StandardInput.line ----------> Write.text

    StandardInput.line ---> Trigger.value
    Trigger.finish -------> ProcessEnd.end
}


