name    = "distributed_work"
version = "0.1.0"

[dependencies]
std      = "0.10.1"
http     = "0.10.1"
net      = "0.10.1"
encoding = "0.10.1"
distrib  = "0.10.1"
work     = "0.10.1"

[entrypoints]
main = "distributed_work/main::main"
