#!/usr/bin/env melodium
#! name = secret_send
#! version = 0.10.4
#! require = std:0.10.4
#! require = distrib:0.10.4

use distrib::DistributionEngine
use distrib::sendBlock

treatment send[distributor: DistributionEngine]()
  input distribution_id: Block<u64>
  input secret: Block<Secret<string>>
{
    sendBlock<Secret<string>>[distributor=distributor](name="secret")

    Self.distribution_id -> sendBlock.distribution_id
    Self.secret -> sendBlock.data
}

treatment main()
{
}
