#!/usr/bin/env melodium
#! name = secret_vault_sql
#! version = 0.11.0
#! require = std:0.11.0 vault:0.11.0 sql:0.11.0

use std/engine/util::startup
use std/engine/log::logError
use std/secret::|locate
use sql::SqlPool
use sql::connect
use sql::connected
use sql::executeRaw
use vault::Vault

treatment main(const address: string, const database: string)
  model vault: Vault(address = address, auth = "token")
  model pool: SqlPool(url = database, password = |locate<string>("vault:kv/data/app/db#password", "db_password", "local", false), acquire_timeout = 2000)
{
    startup()
    connect[sql_pool=pool]()
    startup.trigger -> connect.trigger

    connected[sql_pool=pool]()
    executeRaw[sql_pool=pool](sql="SELECT 1")
    logSqlError: logError(label="sql-error")
    connected.trigger -> executeRaw.trigger,error -> logSqlError.message
}
