
use std/process/engine::Ready
use std/fs/read/mono::ReadPath
use std/fs/write/mono::WritePath
use std/text/encoding::Decode
use std/text/encoding::Encode

sequence Reencoding(const input: string, const output_encoding: string, const output: string)
{
    Ready()
    ReadPath(path=input)
    Decode()
    Encode(encoding=output_encoding)
    WritePath(path=output)
    
    Ready.ready -> ReadPath.trigger,data -> Decode.data,text -> Encode.text,data -> WritePath.data
}

sequence Main()
{
    Re_utf8:      Reencoding(input="./input.txt", output_encoding="utf-8",       output="./output_utf-8.txt"       )
    Re_iso885915: Reencoding(input="./input.txt", output_encoding="iso-8859-15", output="./output_iso-8859-15.txt" )
    Re_ascii:     Reencoding(input="./input.txt", output_encoding="ascii",       output="./output_ascii.txt"       )
    Re_utf16le:   Reencoding(input="./input.txt", output_encoding="utf-16le",    output="./output_utf-16le.txt"    )
    Re_utf16be:   Reencoding(input="./input.txt", output_encoding="utf-16be",    output="./output_utf-16be.txt"    )
}


