name: Mélodium CI on GitHub

on: workflow_dispatch

jobs:
  melodium_github:
    runs-on: registry.gitlab.com/melodium/melodium:alpine-0.9.0-pre.1
    env:
      MELODIUM_HOME: /melodium_home
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Mélodium CI
        run: /melodium run .melodium/Compo.toml main --on_github=true --out_directory "\"./results\"" --key "\"$MELODIUM_SERVICE_KEY\"" --repository_url \"${{ github.repositoryUrl }}\" --ci_token \"${{ github.token }}\" --project_id \"${{ github.repository_id }}\" --owner_id \"${{ github.repository_owner_id }}\" --sha \"${{ github.sha }}\"
      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            results/
      